<?xml version="1.0" encoding="UTF-8"?>

<!-- File was generated by XSLfast 6.0, build 11/09/2012 -->
<!-- Layout version: 7 -->
<!-- Please leave unchanged; manage layouts instead -->
<!DOCTYPE xsl:stylesheet [
<!ENTITY XML "http://www.w3.org/TR/REC-xml">
<!ENTITY XMLNames "http://www.w3.org/TR/REC-xml-names">
<!ENTITY XSLT.ns "http://www.w3.org/1999/XSL/Transform">
<!ENTITY XSLTA.ns "http://www.w3.org/1999/XSL/TransformAlias">
<!ENTITY XSLFO.ns "http://www.w3.org/1999/XSL/Format">
<!ENTITY copy "&#169;">
<!ENTITY trade "&#8482;">
<!ENTITY deg "&#x00b0;">
<!ENTITY gt "&#62;">
<!ENTITY sup2 "&#x00b2;">
<!ENTITY frac14 "&#x00bc;">
<!ENTITY quot "&#34;">
<!ENTITY frac12 "&#x00bd;">
<!ENTITY euro "&#x20ac;">
<!ENTITY Omega "&#937;">
]>


<xsl:stylesheet 
	xmlns:fox="http://xmlgraphics.apache.org/fop/extensions"
	xmlns:NS1="http://www.greco.eu/schemas/2014/GOSPOS"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:fo="http://www.w3.org/1999/XSL/Format" version="2.0"
	xmlns:saxon="http://saxon.sf.net/" extension-element-prefixes="saxon"
	xmlns:xslfast="http://www.xslfast.com">


<xsl:variable name="path" select="document-uri(document(''))" />
<xsl:variable name="path1" select="base-uri()" />
<xsl:variable name="path2" select="static-base-uri()" />
<xsl:variable name="path3" select="replace(base-uri(),'(.*/)[^/]+?.xml','$1')" />

<xsl:variable name="xxslfile" select="codepoints-to-string(reverse(string-to-codepoints(substring-before(codepoints-to-string(reverse(string-to-codepoints($path))), '/'))))"/> <!-- file alleine -->
<xsl:variable name="xxbasedir" select="substring-before($path2,$xxslfile)" /> <!-- Verzeichnis, von dem aus das xsl file geladen wurde -->


<xsl:variable name="common_img" select="concat($xxbasedir,'IMG','/')" />
<xsl:variable name="special_img" select="concat($xxbasedir,'..','/','IMG','/')" />

<xsl:template match="NS1:form">
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
<fo:layout-master-set>
<fo:simple-page-master master-name="masterNamePageTitle0" page-height="845.0pt" page-width="598.0pt" margin-top="0.0pt" margin-left="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="0.0pt" margin-top="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-before extent="0.0pt" precedence="true"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-after extent="0.0pt" precedence="true"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-start extent="0.0pt"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-end extent="0.0pt"  background-position-horizontal="center" background-position-vertical="center" />
</fo:simple-page-master>
<fo:simple-page-master master-name="masterNamePageMain1" page-height="845.0pt" page-width="598.0pt" margin-top="0.0pt" margin-left="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="42.68pt" margin-top="113.81pt" margin-bottom="71.13pt" margin-right="39.83pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-before extent="113.81pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-after extent="71.13pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-start extent="42.68pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-end extent="39.83pt"  background-position-horizontal="left" background-position-vertical="top" />
</fo:simple-page-master>
<fo:simple-page-master master-name="masterNamePageOther2" page-height="845.0pt" page-width="598.0pt" margin-top="0.0pt" margin-left="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="0.0pt" margin-top="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-before extent="0.0pt" precedence="true"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-after extent="0.0pt" precedence="true"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-start extent="0.0pt"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-end extent="0.0pt"  background-position-horizontal="center" background-position-vertical="center" />
</fo:simple-page-master>
</fo:layout-master-set>
<fo:bookmark-tree> </fo:bookmark-tree>
<fo:page-sequence master-reference="masterNamePageTitle0" format="1">
<xsl:attribute name="force-page-count">no-force</xsl:attribute>
<fo:static-content flow-name="xsl-region-before">
<fo:block-container position="absolute" top="-2.85pt" left="0.0pt" height="142.0pt" width="284.0pt" display-align="before" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="142.0pt" width="284.0pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:choose>
<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Titelseite_GrECo_HPF.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Titelseite_VMG_HPF.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Titelseite_BACA_HPF.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Titelseite_EGHV_HPF.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Titelseite_GrECo_HPF.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Titelseite_CMV_HPF.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:otherwise>
	<fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Titelseite_GrECo_HPF.jpg')})" content-width="21.12cm" />
	</fo:block>
</xsl:otherwise>

</xsl:choose></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="xsl-region-after">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="xsl-region-start">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="xsl-region-end">
  <fo:block/>
</fo:static-content>
<fo:flow flow-name="xsl-region-body">
<fo:block/>
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="28.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="14.23pt" end-indent="14.23pt" padding-top="598.08pt" width="569.06pt"  height="36.99pt" ><xsl:variable name="Firmenfarbe_h1_Titel">
<xsl:choose>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
		 <xsl:value-of select="'#E2001A'"/> <!-- Rot VMG 226,0,26-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
		 <xsl:value-of select="'#FF0000'"/> <!-- Rot BA-CA 255,0,0-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
		 <xsl:value-of select="'#005AA1'"/> <!-- Blau GrECo 0,90,161-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>

	<xsl:otherwise>
		 <xsl:value-of select="'green'"/>
	</xsl:otherwise>
</xsl:choose>
</xsl:variable>


<fo:block text-align="center" space-after="8pt">
	<fo:inline font-family="Calibri" font-size="28pt" color="{$Firmenfarbe_h1_Titel}">
		<xsl:if test="NS1:item[@NS1:name='chk_gesamtklauseln']/@NS1:value=''">
			<xsl:value-of select="concat(NS1:item[@NS1:name='drop_konzept_antrag']/@NS1:value,' für ' , NS1:item[@NS1:name='xsl_vertragsaufbau1']/@NS1:value,' ')"/>
			<xsl:value-of select="NS1:item[@NS1:name='xsl_vertragsaufbau2']/@NS1:value"/>
		</xsl:if>
		<xsl:if test="NS1:item[@NS1:name='chk_gesamtklauseln']/@NS1:value='on'">
			<xsl:text>Gesamtklauselpaket</xsl:text>
		</xsl:if>
	</fo:inline>
</fo:block>
</fo:block>
</fo:block-container>
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="center" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="16.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="569.0pt"  height="21.0pt" ><fo:block space-after="6pt" font-family="Calibri" font-size="16pt">
	<xsl:if test="NS1:item[@NS1:name='chk_gesamtklauseln']/@NS1:value=''">
		<xsl:value-of select="concat('für ', NS1:item[@NS1:name='inp_vn']/@NS1:value)"/>
		<xsl:text>&#x0a;</xsl:text>
	</xsl:if>
	<xsl:if test="NS1:item[@NS1:name='chk_gesamtklauseln']/@NS1:value='on'">
		<xsl:value-of select="concat('Auswahl: ', NS1:item[@NS1:name='drop_versicherer']/@NS1:value)"/>
		<xsl:text>&#x0a;</xsl:text>
	</xsl:if>
</fo:block>

<fo:block font-family="Calibri" font-size="11pt">
	<xsl:value-of select="concat('erstellt am ', NS1:item[@NS1:name='xsl_erstellungsdatum']/@NS1:value)"/>
</fo:block>

</fo:block>
</fo:block-container>
</fo:flow>
</fo:page-sequence>
<fo:page-sequence master-reference="masterNamePageMain1" format="1">
<xsl:attribute name="force-page-count">no-force</xsl:attribute>
<fo:static-content flow-name="xsl-region-before">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="100.0pt"  height="30.0pt" ><xsl:choose>
<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_GrECo.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_VMG.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_BACA.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_EGHV.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_GrECo.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_CMV.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:when>

<xsl:otherwise>
	<fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_GrECo.jpg')})" content-width="21.12cm" />
	</fo:block>
</xsl:otherwise>

</xsl:choose></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="xsl-region-after">
<fo:block-container position="absolute" top="28.5pt" left="256.36pt" height="22.76pt" width="85.36pt" display-align="after" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="center" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="22.76pt" width="85.36pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='VMG'">
	<xsl:text>Seite </xsl:text>
	<fo:page-number/>
</xsl:if></fo:block>
</fo:block-container>
<fo:block-container position="absolute" top="28.5pt" left="472.88pt" height="22.76pt" width="85.36pt" display-align="after" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="22.76pt" width="85.36pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value!='VMG'">
	<xsl:text>Seite </xsl:text>
	<fo:page-number/>
</xsl:if></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="xsl-region-start">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="xsl-region-end">
  <fo:block/>
</fo:static-content>
<fo:flow flow-name="xsl-region-body">
<fo:block/>
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="436.0pt"  height="30.0pt" ><xsl:variable name="Firmenfarbe_h1_z">
<xsl:choose>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
		 <xsl:value-of select="'#E2001A'"/> <!-- Rot VMG 226,0,26-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
		 <xsl:value-of select="'#FF0000'"/> <!-- Rot BA-CA 255,0,0-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
		 <xsl:value-of select="'#005AA1'"/> <!-- Blau GrECo 0,90,161-->
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>

	<xsl:otherwise>
		 <xsl:value-of select="'green'"/>
	</xsl:otherwise>
</xsl:choose>
</xsl:variable>


<!--
<xsl:if test="NS1:item[@NS1:name='chk_gesamtklauseln']/@NS1:value=''">
	<xsl:call-template name="Zusammenfassung">
	</xsl:call-template>
	<fo:block page-break-after="always"></fo:block>
</xsl:if>
-->

<fo:block-container>
	<fo:block position="relative" font-family="Calibri" font-size="10pt" text-align="left">
		<fo:table text-align="left" vertical-align="center" padding-top="0.3cm" padding-bottom="0.3cm" >
			<fo:table-column column-width="25%" border="0.02cm" border-style="solid"/>
			<fo:table-column column-width="25%" border="0.02cm" border-style="solid"/>
			<fo:table-column column-width="25%" border="0.02cm" border-style="solid"/>
			<fo:table-column column-width="25%" border="0.02cm" border-style="solid"/>


<fo:table-header border-style="none">                            
      <fo:table-row >                         
        <fo:table-cell number-columns-spanned="4">                      
	<fo:block text-align="center" space-after="8pt">
		<fo:inline font-family="Calibri" font-size="16pt" color="{$Firmenfarbe_h1_z}">
		<xsl:text>Richtindikation</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:choose>
			<xsl:when test="NS1:item[@NS1:name='DO']/@NS1:value = 'true' and NS1:item[@NS1:name='SRS']/@NS1:value = 'true'" >
				<xsl:text>D&amp;O und Unternehmens-Strafrechtsschutzversicherung</xsl:text>
			</xsl:when>
			<xsl:when test="NS1:item[@NS1:name='DO']/@NS1:value = 'true' and NS1:item[@NS1:name='SRS']/@NS1:value = 'false'" >
				<xsl:text>D&amp;O Versicherung</xsl:text>
			</xsl:when>		
			<xsl:otherwise>
				<xsl:text>Unternehmens-Strafrechtsschutzversicherung</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
		</fo:inline>
	</fo:block>			
        </fo:table-cell>
     </fo:table-row>
</fo:table-header>
			
			
			
			<fo:table-body>
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>VersicherungsnehmerIn</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell number-columns-spanned="3" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:value-of select="concat(NS1:item[@NS1:name='name_client']/@NS1:value,', ',NS1:item[@NS1:name='street_client']/@NS1:value, ', ',NS1:item[@NS1:name='zip_client']/@NS1:value, ' ', NS1:item[@NS1:name='city_client']/@NS1:value,', ',NS1:item[@NS1:name='trade_register_no_client']/@NS1:value)" />
						</fo:block>
					</fo:table-cell>
				</fo:table-row>
		

<!-- DO relevant? -->
<xsl:if test="NS1:item[@NS1:name='DO']/@NS1:value='true'" >
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>D&amp;O</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Deckungssumme</xsl:text>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<!-- <xsl:text>EUR 1.000.000,00</xsl:text> -->
								<xsl:value-of select="concat('EUR ',translate(format-number(number(NS1:item[@NS1:name='turnover_do']/@NS1:value),'#,##0.00'),'.,',',.'))" />
							</fo:block>
							<fo:block>
								<!-- <xsl:text>EUR 3.000.000,00</xsl:text> -->
								<xsl:value-of select="concat('EUR ',translate(format-number(number(NS1:item[@NS1:name='sum_insured_do']/@NS1:value),'#,##0.00'),'.,',',.'))" />
							</fo:block>							
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block font-weight="bold">
							<xsl:text>Jahres-Nettoprämie</xsl:text>
							<fo:block font-weight="bold">
								<xsl:text>zzgl. 11% VSt</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<!-- <xsl:text>EUR 1.500,00</xsl:text> -->
								<xsl:value-of select="concat('EUR ',translate(format-number(number(NS1:item[@NS1:name='premium_do']/@NS1:value),'#,##0.00'),'.,',',.'))" />
							</fo:block>
							<fo:block>
								<xsl:text>EUR 3.150,00</xsl:text>
							</fo:block>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block font-weight="bold">
							<xsl:text>Jahres-Bruttoprämie</xsl:text>
							<fo:block font-weight="bold">
								<xsl:text>inkl. 11% VSt</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>EUR</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>EUR</xsl:text>
							</fo:block>								
						</fo:block>
					</fo:table-cell>
				</fo:table-row>
	</xsl:if>				


<!-- SRS relevant? -->
<xsl:if test="NS1:item[@NS1:name='SRS']/@NS1:value='true'" >
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>StrRS</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Deckungssumme</xsl:text>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>EUR 500.000,00</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>EUR 1.000.000,00</xsl:text>
							</fo:block>							
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block font-weight="bold">
							<xsl:text>Jahres-Nettoprämie</xsl:text>
							<fo:block font-weight="bold">
								<xsl:text>zzgl. 11% VSt</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>EUR 750,00</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block font-weight="bold">
							<xsl:text>Jahres-Bruttoprämie</xsl:text>
							<fo:block font-weight="bold">
								<xsl:text>inkl. 11% VSt</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>EUR</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>								
						</fo:block>
					</fo:table-cell>
				</fo:table-row>
	</xsl:if>					

<!-- Assekuradeur -->
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Assekuradeur</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm" number-columns-spanned="3">
							<fo:block>
								<xsl:text>DUAL Deutschland GmbH</xsl:text>
							<fo:block>
								<xsl:text>Schanzenstraße 36 / Gebäude 197</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>51063 Köln</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>für den vertretenen Versicherer</xsl:text>
							</fo:block>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>

<!-- Versicherer DO -->
<xsl:if test="NS1:item[@NS1:name='DO']/@NS1:value='true'" >
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Versicherer D&amp;O</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm" number-columns-spanned="3">
							<fo:block>
								<xsl:text>Liberty Mutual Insurance Europe Ltd.</xsl:text>
							<fo:block>
								<xsl:text>23rd Floor, 20 Fenchurch Street</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>EC3M 3AW London</xsl:text>
							</fo:block>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>


<!-- Bedingungen DO -->
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Bedingungen D&amp;O</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm" number-columns-spanned="3">
							<fo:block>
								<xsl:text>Dual AVBDO 2018 GrECo (2018/04)</xsl:text>
							</fo:block>
					</fo:table-cell>
				</fo:table-row>
</xsl:if>


<!-- Versicherer SRS -->
<xsl:if test="NS1:item[@NS1:name='SRS']/@NS1:value='true'" >
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Versicherer StrRS</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm" number-columns-spanned="3">
							<fo:block>
								<xsl:text>Everest Insurance (Ireland), DAC</xsl:text>
							<fo:block>
								<xsl:text>Huguenot House</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>35-38 St. Stephen's Green</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>Dublin 2 D02NY63</xsl:text>
							</fo:block>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>


<!-- Bedingungen SRS -->
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Bedingungen StrRS</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm" number-columns-spanned="3">
							<fo:block>
								<xsl:text>Dual AVBST 2018 GrECo (2018/04)</xsl:text>
							</fo:block>
					</fo:table-cell>
				</fo:table-row>
</xsl:if>

<!-- Voraussetzungen -->
<!-- Bedingungen SRS -->
				<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
					<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
						<fo:block>
							<xsl:text>Voraussetzungen für ein verbindliches Angebot</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm" number-columns-spanned="3">
							<fo:block>
								<xsl:text>Bei den oben genannten Prämien handelt es sich um Richtprämien.</xsl:text>
							</fo:block>
							<fo:block font-size="4pt">
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>Eine Verbindlichstellung kann erst nach positiver Bewertung des Fragebogens erfolgen. Dieser ist</xsl:text>
							</fo:block>
							<fo:block font-size="4pt">
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block padding-left="1cm">
								<xsl:text>- vollständig auszufüllen</xsl:text>
							</fo:block>
							<fo:block padding-left="1cm">
								<xsl:text>- rechtsgültig (von einem Geschäftsführer) zu unterzeichnen und</xsl:text>
							</fo:block>
							<fo:block padding-left="1cm">
								<xsl:text>- aktuell zu datieren (bei Vertragsbeginn nicht älter als 12 Wochen)</xsl:text>
							</fo:block>
							<fo:block padding-left="1cm" font-size="4pt">
								<xsl:text>&#x0a;</xsl:text>
							</fo:block>
							<fo:block>
								<xsl:text>Ein verbindliches Angebot gilt frei von bekannten pflichtverletzungen (sofern nicht abweichend vereinbart) und basiert auf den Angaben der vorgelegten Risikoinformationen.</xsl:text>
							</fo:block>							
					</fo:table-cell>
				</fo:table-row>
				
			</fo:table-body>
		</fo:table>
</fo:block>		
</fo:block-container></fo:block>
</fo:block-container>
</fo:flow>
</fo:page-sequence>
<fo:page-sequence master-reference="masterNamePageOther2" format="1">
<xsl:attribute name="force-page-count">no-force</xsl:attribute>
<fo:static-content flow-name="xsl-region-before">
<fo:block-container position="absolute" top="-2.85pt" left="0.0pt" height="142.26pt" width="284.53pt" display-align="before" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="142.26pt" width="284.53pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:choose>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Endseite_GrECo.jpg')})" content-height="29.85cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Endseite_VMG.jpg')})" content-height="29.85cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Endseite_BACA.jpg')})" content-height="29.85cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Endseite_EGHV.jpg')})" content-height="29.85cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Endseite_GrECo.jpg')})" content-height="29.85cm" />
   </fo:block>
</xsl:when>

<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Endseite_CMV.jpg')})" content-height="29.85cm" />
   </fo:block>
</xsl:when>

<xsl:otherwise>
	<fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Endseite_GrECo.jpg')})" content-height="29.85cm" />
	</fo:block>
</xsl:otherwise>

</xsl:choose></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="xsl-region-after">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="xsl-region-start">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="xsl-region-end">
  <fo:block/>
</fo:static-content>
<fo:flow flow-name="xsl-region-body">
<fo:block/>
<fo:block-container position="absolute" top="611.73pt" left="85.36pt" height="96.74pt" width="427.36pt" display-align="before" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="center" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="10.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="96.74pt" width="427.36pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:call-template name="Firmendaten_Endseite"></xsl:call-template></fo:block>
</fo:block-container>
<xsl:if test='position()=last()'>
  <fo:block id="lastPage"/>
</xsl:if>
</fo:flow>
</fo:page-sequence>
</fo:root>
</xsl:template>

<!-- GENERATED TEMPLATE Firmendaten_Endseite -->
<xsl:template name="Firmendaten_Endseite" >
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="427.36pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="427.36pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="10.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='GrECo'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="14pt" color="#005AA1"> <!-- Blau GrECo 0,90,161-->
		<xsl:text>GrECo International AG</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>


<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='VMG'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="14pt" color="#00518F"> <!-- Blau VMG 0,81,143-->
		<xsl:text>VMG Versicherungsmakler GmbH</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='BA-CA'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="14pt" color="black">
		<xsl:text>BA</xsl:text>
	</fo:inline>
	<fo:inline font-family="Calibri" font-size="14pt" color="#FF0000"> <!-- Rot BA-CA 255,0,0-->
		<xsl:text>~</xsl:text>
	</fo:inline>
	<fo:inline font-family="Calibri" font-size="14pt" color="black">
		<xsl:text>CA GrECo Versicherungsmanagement GmbH</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>


<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='EGHV'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="14pt" color="#005AA1"> <!-- Blau GrECo 0,90,161-->
		<xsl:text>Ecclesia GrECo Hospital Versicherungsmakler GmbH</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='GJRC'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="14pt" color="#005AA1"> <!-- Blau GrECo 0,90,161-->
		<xsl:text>GrECo JLT Risk Consulting GmbH</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='CMV'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="14pt" color="#005AA1"> <!-- Blau GrECo 0,90,161-->
		<xsl:text>CMV - Christian Mädel Versicherungsmakler GmbH</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="427.36pt"  reference-orientation="0">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="10.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt"><xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='GrECo'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="10pt" color="black">
		<xsl:text>Versicherungsmakler und Berater in</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Versicherungsangelegenheiten</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>1191 Wien, Elmargasse 2-4</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Reg.Nr.: 24158374</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Tel.: +43 (0)5 04 04-0</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Fax: +43 (0)5 04 04-11 999</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>office@greco.at</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='VMG'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="10pt" color="black">
		<xsl:text>Versicherungsmakler und Berater in</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Versicherungsangelegenheiten</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>1090 Wien, Berggasse 31</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Reg.Nr.: 23793750</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Tel.: +43 (0)50 100-78 000</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Fax: +43 (0)50 100 9-78 000</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>office@vmg.at</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='BA-CA'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="10pt" color="black">
		<xsl:text>Versicherungsmakler und Berater in</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Versicherungsangelegenheiten</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>1191 Wien, Elmargasse 2-4</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Reg.Nr.: 24225823</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Tel.: +43 (0)5 04 04-0</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Fax: +43 (0)5 04 04-11 999</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>office@greco.at</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='EGHV'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="10pt" color="black">
		<xsl:text>Versicherungsmakler und Berater in</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Versicherungsangelegenheiten</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>1190 Wien, Elmargasse 2-4</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Reg.Nr.: 24681513</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Tel.: +43 (0)5 04 04-0</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Fax: +43 (0)5 04 04-11 999</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>office@eghv.at</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='GJRC'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="10pt" color="black">
		<xsl:text>Versicherungsmakler und Berater in</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Versicherungsangelegenheiten</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>1190 Wien, Elmargasse 2-4</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Reg.Nr.: 25267365</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Tel.: +43 (0)5 04 04-0</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Fax: +43 (0)5 04 04-11 999</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>office@greco.at</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='CMV'">
<fo:block text-align="center">
	<fo:inline font-family="Calibri" font-size="10pt" color="black">
		<xsl:text>Versicherungsmakler und Berater in</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Versicherungsangelegenheiten</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>1190 Wien, Hungerbergstraße 1A/5</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Reg.Nr.: 23736153</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Tel.: +43 1 478 95 00</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>Fax: +43 1 478 95 01</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:text>office@cmv.at</xsl:text>
	</fo:inline>
</fo:block>
</xsl:if></fo:block>
</fo:block-container>
</fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>
<xsl:template match="include-xsl-fo">
    <xsl:copy-of select="@*"/>
</xsl:template>
</xsl:stylesheet>
