<?xml version="1.0" encoding="UTF-8"?>

<!-- File was generated by XSLfast 6.0, build 11/09/2012 -->
<!-- Layout version: 7 -->
<!-- Please leave unchanged; manage layouts instead -->
<!DOCTYPE xsl:stylesheet [
<!ENTITY XML "http://www.w3.org/TR/REC-xml">
<!ENTITY XMLNames "http://www.w3.org/TR/REC-xml-names">
<!ENTITY XSLT.ns "http://www.w3.org/1999/XSL/Transform">
<!ENTITY XSLTA.ns "http://www.w3.org/1999/XSL/TransformAlias">
<!ENTITY XSLFO.ns "http://www.w3.org/1999/XSL/Format">
<!ENTITY copy "&#169;">
<!ENTITY trade "&#8482;">
<!ENTITY deg "&#x00b0;">
<!ENTITY gt "&#62;">
<!ENTITY sup2 "&#x00b2;">
<!ENTITY frac14 "&#x00bc;">
<!ENTITY quot "&#34;">
<!ENTITY frac12 "&#x00bd;">
<!ENTITY euro "&#x20ac;">
<!ENTITY Omega "&#937;">
]>


<xsl:stylesheet 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:func="http://exslt.org/functions"
	xmlns:exslt="http://exslt.org/common"
	xmlns:fox="http://xmlgraphics.apache.org/fop/extensions"
	xmlns:saxon="http://saxon.sf.net/" extension-element-prefixes="saxon"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xslfast="http://www.xslfast.com"
	xmlns:common="http://exslt.org/common"
	xmlns:fo="http://www.w3.org/1999/XSL/Format" version="2.0"
	xmlns:msxsl="urn:schemas-microsoft-com:xslt"
	xmlns:NS1="http://www.greco.eu/schemas/2014/GOSPOS">


<xsl:variable name="path" select="document-uri(document(''))" />
<xsl:variable name="path1" select="base-uri()" />
<xsl:variable name="path2" select="static-base-uri()" />
<xsl:variable name="path3" select="replace(base-uri(),'(.*/)[^/]+?.xml','$1')" />

<xsl:variable name="xxslfile" select="codepoints-to-string(reverse(string-to-codepoints(substring-before(codepoints-to-string(reverse(string-to-codepoints($path))), '/'))))"/> <!-- file alleine -->
<xsl:variable name="xxbasedir" select="substring-before($path2,$xxslfile)" /> <!-- Verzeichnis, von dem aus das xsl file geladen wurde -->


<xsl:variable name="common_img" select="concat($xxbasedir,'IMG','/')" />
<xsl:variable name="special_img" select="concat($xxbasedir,'..','/','IMG','/')" />

<xsl:template match="NS1:form">
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
<fo:layout-master-set>
<fo:simple-page-master master-name="masterNamePageMain0" page-height="845.0pt" page-width="598.0pt" margin-top="0.0pt" margin-left="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="56.91pt" margin-top="71.13pt" margin-bottom="85.36pt" margin-right="56.91pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-before extent="71.13pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-after extent="85.36pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-start extent="56.91pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-end extent="56.91pt"  background-position-horizontal="left" background-position-vertical="top" />
</fo:simple-page-master>
<fo:simple-page-master master-name="masterNamePageFirst1" page-height="845.0pt" page-width="598.0pt" margin-top="28.45pt" margin-left="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="56.91pt" margin-top="71.13pt" margin-bottom="85.36pt" margin-right="56.91pt"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-before region-name="regionBefore1" extent="71.13pt" precedence="true"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-after region-name="regionAfter1" extent="85.36pt" precedence="true"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-start region-name="regionStart1" extent="56.91pt"  background-position-horizontal="center" background-position-vertical="center" />
<fo:region-end region-name="regionEnd1" extent="56.91pt"  background-position-horizontal="center" background-position-vertical="center" />
</fo:simple-page-master>
<fo:simple-page-master master-name="masterNamePageRest2" page-height="845.0pt" page-width="598.0pt" margin-top="28.45pt" margin-left="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="56.91pt" margin-top="71.13pt" margin-bottom="85.36pt" margin-right="56.91pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-before region-name="regionBefore2" extent="71.13pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-after region-name="regionAfter2" extent="85.36pt" precedence="true"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-start region-name="regionStart2" extent="56.91pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-end region-name="regionEnd2" extent="56.91pt"  background-position-horizontal="left" background-position-vertical="top" />
</fo:simple-page-master>
<fo:page-sequence-master master-name="masterSequenceName1">
<fo:repeatable-page-master-alternatives>
<fo:conditional-page-master-reference master-reference="masterNamePageFirst1" page-position="first"/>
<fo:conditional-page-master-reference master-reference="masterNamePageRest2" page-position="rest"/>
</fo:repeatable-page-master-alternatives>
</fo:page-sequence-master>
</fo:layout-master-set>
<fo:bookmark-tree> </fo:bookmark-tree>
<fo:page-sequence master-reference="masterSequenceName1" format="1">
<xsl:attribute name="force-page-count">no-force</xsl:attribute>
<fo:static-content flow-name="regionBefore1">
<fo:block-container>
<fo:block text-align="center">
	    <fo:external-graphic src="url({concat($common_img,'dual_logo.png')})" content-width="4.8cm" />
</fo:block>
</fo:block-container></fo:static-content>
<fo:static-content flow-name="regionAfter1">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="100.0pt"  height="30.0pt" ><fo:block absolute-position="absolute" top="25cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'dual_first_page_footer.png')})" content-width="21.12cm" />
</fo:block>
</fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="regionStart1">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="regionEnd1">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="regionBefore2">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="regionAfter2">
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="100.0pt"  height="30.0pt" ><fo:block absolute-position="absolute" top="25cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'dual_policy_footer.png')})" content-width="21.12cm" />
</fo:block>
</fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="regionStart2">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="regionEnd2">
  <fo:block/>
</fo:static-content>
<fo:flow flow-name="xsl-region-body">
<fo:block/>
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="center" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" line-height="14.5pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="328.0pt"  height="45.0pt" ><xsl:call-template name="rechnung_DO" /></fo:block>
</fo:block-container>
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" line-height="14.5pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="320.0pt"  height="30.0pt" ><fo:block-container space-before="2cm" >
	<fo:block position="relative" font-family="Arial" font-size="10pt"  >
		<fo:table text-align="left"   table-omit-header-at-break="true">
			<fo:table-column column-width="50%" text-align="left"/>
			<fo:table-column column-width="50%" text-align="right"/>

			<fo:table-body>
			
				<fo:table-row  height="12pt">
					<fo:table-cell   number-columns-spanned="2">
						<fo:block text-align="right">
							<xsl:value-of select="format-date(current-date(),'[D01].[M01].[Y0001]')"/>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>

<!-- Leerzeile -->
				<fo:table-row  height="12pt">
					<fo:table-cell   number-columns-spanned="2">
						<fo:block>
							<xsl:text></xsl:text>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>

				
				<fo:table-row  height="10pt" >					
					<fo:table-cell   number-columns-spanned="2">
						<fo:block font-size="12pt" text-align="left" font-style="bold">
							<xsl:value-of select="'Prämienrechnung zur D&amp;O-Versicherung Nr.: '"/>
							<xsl:value-of select="NS1:item[@NS1:name='policy_no_do']/@NS1:value" />
						</fo:block>
						<fo:block>
							<fo:inline font-size="8pt" height="8pt">Erstellt im Auftrag und mit Vollmacht des Versicherers.</fo:inline>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>


<!-- Leerzeile -->
				<fo:table-row  height="24pt">
					<fo:table-cell   number-columns-spanned="2">
						<fo:block>
							<xsl:text></xsl:text>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>



				<fo:table-row  height="12pt">
					<fo:table-cell number-columns-spanned="2">
						<fo:block>
							<xsl:text>Fälligkeit: </xsl:text>
							<xsl:value-of select="NS1:item[@NS1:name='due_date_do']/@NS1:value" />
						</fo:block>
					</fo:table-cell>
				</fo:table-row>

<!-- Leerzeile -->
				<fo:table-row  height="12pt">
					<fo:table-cell   number-columns-spanned="2">
						<fo:block>
							<xsl:text></xsl:text>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>
				

				<fo:table-row  height="12pt">
					<fo:table-cell text-align="left">
						<fo:block>
							<xsl:text>Abrechnungszeitraum:</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell text-align="right">
						<fo:block>
							<xsl:text>Abrechnungsbetrag EUR:</xsl:text>
						</fo:block>
					</fo:table-cell>					
				</fo:table-row>	
	
				<fo:table-row  height="12pt">				
					<fo:table-cell text-align="left" number-columns-spanned="2">
						<fo:block>
							<xsl:value-of select="concat('vom ',NS1:item[@NS1:name='begin_date_do']/@NS1:value, ' bis ',NS1:item[@NS1:name='end_date_do']/@NS1:value)" />
						</fo:block>
					</fo:table-cell>
				</fo:table-row>	

<!-- Leerzeile -->
				<fo:table-row  height="12pt">
					<fo:table-cell   number-columns-spanned="2">
						<fo:block>
							<xsl:text></xsl:text>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>



				<fo:table-row  height="12pt">
					<fo:table-cell text-align="left">
						<fo:block>
							<xsl:text>Gesamt:</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell text-align="right">
						<fo:block>
							<xsl:value-of select="translate(format-number(number(NS1:item[@NS1:name='premium_do']/@NS1:value),'#,##0.00'),'.,',',.')" />
						</fo:block>
					</fo:table-cell>					
				</fo:table-row>	


				<fo:table-row  height="12pt">
					<fo:table-cell text-align="left">
						<fo:block>
							<xsl:text>Versicherungssteuer 11,00 %:</xsl:text>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell text-align="right">
						<fo:block>
							<xsl:value-of select="translate(format-number(number(NS1:item[@NS1:name='premium_do']/@NS1:value*0.11),'#,##0.00'),'.,',',.')" />
						</fo:block>
					</fo:table-cell>					
				</fo:table-row>	

      <fo:table-row>                                           
         <fo:table-cell number-columns-spanned="2"> 
            <fo:block text-align="start">
        	<fo:leader leader-pattern="rule"
                   rule-thickness="0.1pt"
                   leader-length="17.3cm"
                   start-indent="0cm"
                   end-indent="0cm"
                   color="black"/>
	    </fo:block>
         </fo:table-cell>
      </fo:table-row>


				<fo:table-row  height="12pt">
					<fo:table-cell text-align="left" >
						<fo:block>
							<xsl:text>Zu zahlender Gesamtbetrag:</xsl:text>
						</fo:block>
						<fo:block>
							<fo:inline font-size="8pt">Versicherungsbeiträge sind umsatzsteuerfrei gem. § 6 UstG.</fo:inline>
						</fo:block>
					</fo:table-cell>
					<fo:table-cell text-align="right">
						<fo:block font-style="bold">
							<xsl:value-of select="translate(format-number(number(NS1:item[@NS1:name='premium_do']/@NS1:value*1.11),'#,##0.00'),'.,',',.')" />
						</fo:block>
					</fo:table-cell>					
				</fo:table-row>	


      <fo:table-row>                                           
         <fo:table-cell number-columns-spanned="2"> 
            <fo:block text-align="start">
        	<fo:leader leader-pattern="rule"
                   rule-thickness="0.1pt"
                   leader-length="17.3cm"
                   start-indent="0cm"
                   end-indent="0cm"
                   color="black"/>
	    </fo:block>
         </fo:table-cell>
      </fo:table-row>




			</fo:table-body>
</fo:table>
</fo:block>
</fo:block-container></fo:block>
</fo:block-container>
<fo:block break-before="auto"/>
<fo:block-container height="25.61pt" width="439.0pt" font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="11.67pt" white-space-collapse="false"  hyphenate="true" language="en"  space-before="28.45pt" space-before.conditionality="retain" text-align="start" width="439.0pt"  height="25.61pt"  keep-together="auto"  letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>Bitte überweisen Sie den Gesamtbetrag auf unser Konto:</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>Nr.: 310 551 388</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>Kreissparkasse Köln</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>BLZ 370 502 99</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>IBAN: DE03 3705 0299 0310 5513 88</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>SWIFT-BIC: COKSDE33</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="9.0pt" text-decoration="underline">
<fo:inline text-decoration="underline"><xsl:text>Besonderer Hinweis:</xsl:text></fo:inline></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="9.0pt">
<xsl:text>Wir ersuchen Sie unter Hinweis auf die Rechtsfolgen nicht termingerechter Zahlung (gemäß § 38 Versicherungsvertragsgesetz - vgl. Rückseite) die Erstprämie binnen 14 Tagen zu entrichten. Der Versicherungsschutz beginnt erst mit der Zahlung der Prämie.</xsl:text></fo:inline>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" line-height="14.5pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="328.0pt"  height="30.0pt" ><fo:block page-break-before="always">
	<xsl:call-template name="Hinweis" />
</fo:block></fo:block>
</fo:block-container>
<xsl:if test='position()=last()'>
  <fo:block id="lastPage"/>
</xsl:if>
</fo:flow>
</fo:page-sequence>
</fo:root>
</xsl:template>

<!-- GENERATED TEMPLATE rechnung_DO -->
<xsl:template name="rechnung_DO" >
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="436.0pt"  height="22.76pt" >
<xsl:variable name="broker_name">
<xsl:choose>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
		 <xsl:text>GrECo International AG</xsl:text>
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
		 <xsl:text>VMG Versicherungsmakler GmbH</xsl:text>
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
		 <xsl:text>BA~CA GrECo Versicherungsmanagement GmbH</xsl:text>
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
		 <xsl:text>Ecclesia GrECo Hospital Versicherungsmakler GmbH</xsl:text>
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
		 <xsl:text>GrECo JLT Risk Consulting GmbH</xsl:text>
	</xsl:when>

	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
		 <xsl:text>CMV - Christian Mädel Versicherungsmakler GmbH</xsl:text>
	</xsl:when>
</xsl:choose>
</xsl:variable>


<xsl:variable name="broker_street">
<xsl:choose>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
		 <xsl:text>QBC Gertrude-Fröhlich-Sandnerplatz 3</xsl:text>
	</xsl:when>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
		 <xsl:text>Hungerbergstraße 1A/5</xsl:text>
	</xsl:when>
	<xsl:otherwise>
		<xsl:text>Elmargasse 2-4</xsl:text>
	</xsl:otherwise>
</xsl:choose>
</xsl:variable>


<xsl:variable name="broker_zip_city">
<xsl:choose>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
		 <xsl:text>1030 Wien</xsl:text>
	</xsl:when>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
		 <xsl:text>1190 Wien</xsl:text>
	</xsl:when>
	<xsl:otherwise>
		<xsl:text>1191 Wien</xsl:text>
	</xsl:otherwise>
</xsl:choose>
</xsl:variable>



<xsl:variable name="broker_country">
	 <xsl:text>ÖSTERREICH</xsl:text>
</xsl:variable>
<!-- ####################################################################### -->


<fo:block-container>
	<fo:block position="relative" font-family="Arial" font-size="11pt"  >
		<fo:table text-align="left"   table-omit-header-at-break="true">
			<fo:table-column column-width="50%" text-align="left"/>
			<fo:table-column column-width="50%" text-align="right"/>

			<fo:table-body>
			
				<fo:table-row  height="12pt">
					<fo:table-cell   number-columns-spanned="2">
						<fo:block font-size="8pt" text-decoration="underline" text-align="left">
							<xsl:text>DUAL Deutschland GmbH Schanzenstraße 36 / Gebäude 197 51063 Köln</xsl:text>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>
				
				<fo:table-row  height="12pt" >					
					<fo:table-cell   number-columns-spanned="2">
						<fo:block font-size="12pt" text-align="right" text-decoration="underline">
							<xsl:text>Es betreut Sie:</xsl:text>
						</fo:block>
					</fo:table-cell>
				</fo:table-row>

				<fo:table-row>					
					<fo:table-cell   text-align="left">
							<fo:block>
								<xsl:value-of select="NS1:item[@NS1:name='name_client']/@NS1:value" />
							</fo:block>
					</fo:table-cell>
					<fo:table-cell   text-align="right">
							<fo:block>
								<xsl:value-of select="$broker_name" />
							</fo:block>
					</fo:table-cell>
				</fo:table-row>					

				<fo:table-row >					
					<fo:table-cell   text-align="left">
							<fo:block>
								<xsl:value-of select="NS1:item[@NS1:name='street_client']/@NS1:value" />
							</fo:block>
					</fo:table-cell>
					<fo:table-cell   text-align="right">
							<fo:block>
								<xsl:value-of select="$broker_street" />
							</fo:block>
					</fo:table-cell>
				</fo:table-row>

				<fo:table-row >					
					<fo:table-cell   text-align="left">
							<fo:block>
								<xsl:value-of select="concat(NS1:item[@NS1:name='zip_client']/@NS1:value, ' ', NS1:item[@NS1:name='city_client']/@NS1:value)" />
							</fo:block>
					</fo:table-cell>
					<fo:table-cell   text-align="right">
							<fo:block>
								<xsl:value-of select="$broker_zip_city" />
							</fo:block>
					</fo:table-cell>
				</fo:table-row>				
					
				<fo:table-row  >					
					<fo:table-cell   text-align="left">
							<fo:block>
								<xsl:value-of select="NS1:item[@NS1:name='country_client']/@NS1:value" />
							</fo:block>
					</fo:table-cell>
					<fo:table-cell   text-align="right">
							<fo:block>
								<xsl:value-of select="$broker_country" />
							</fo:block>
					</fo:table-cell>
				</fo:table-row>				

			</fo:table-body>
</fo:table>
</fo:block>
</fo:block-container></fo:block>
</fo:block-container>
</xsl:template>

<!-- GENERATED TEMPLATE Hinweis -->
<xsl:template name="Hinweis" >
<fo:block break-before="auto"/>
<fo:block-container height="30.0pt" width="483.7pt" font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="start" width="483.7pt"  height="30.0pt"  keep-together="auto"  letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt" font-weight="bold">
<xsl:text>HINWEIS FÜR DEN VERSICHERUNGSNEHMER</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt" font-weight="bold">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt" font-weight="bold">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>Die umseitig angesprochenen Bestimmungen des</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>Versicherungsvertragsgesetzes lauten:</xsl:text></fo:inline>
<fo:block text-align="center" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>(1) Ist die erste oder einmalige Prämie innerhalb von 14 Tagen nach dem Abschluß des Versicherungsvertrags und nach der Aufforderung zur Prämienzahlung nicht gezahlt, so ist der Versicherer, solange die Zahlung nicht bewirkt ist, berechtigt, vom Vertrag zurückzutreten. Es gilt als Rücktritt, wenn der Anspruch auf die Prämie nicht innerhalb dreier Monate vom Fälligkeitstag an gerichtlich geltend gemacht wird.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>(2) Ist die erste oder einmalige Prämie zur Zeit des Eintritts des Versicherungsfalls und nach Ablauf der Frist des Abs. 1 noch nicht gezahlt, so ist der Versicherer von der Verpflichtung zur Leistung frei, es sei denn, daß der Versicherungsnehmer an der rechtzeitigen Zahlung der Prämie ohne sein Verschulden verhindert war.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>(3) Die Aufforderung zur Prämienzahlung hat die im Abs. 1 und 2 vorgesehenen Rechtsfolgen nur, wenn der Versicherer den Versicherungsnehmer dabei auf diese hingewiesen hat.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>(4) Die Nichtzahlung von Zinsen oder Kosten löst die Rechtsfolgen der Abs. 1 und 2 nicht aus.</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Arial" font-size="11.0pt">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>
<xsl:template match="include-xsl-fo">
    <xsl:copy-of select="@*"/>
</xsl:template>
</xsl:stylesheet>
