<?xml version="1.0" encoding="UTF-8"?>

<!-- File was generated by XSLfast 6.0, build 11/09/2012 -->
<!-- Layout version: 7 -->
<!-- Please leave unchanged; manage layouts instead -->
<!DOCTYPE xsl:stylesheet [
<!ENTITY XML "http://www.w3.org/TR/REC-xml">
<!ENTITY XMLNames "http://www.w3.org/TR/REC-xml-names">
<!ENTITY XSLT.ns "http://www.w3.org/1999/XSL/Transform">
<!ENTITY XSLTA.ns "http://www.w3.org/1999/XSL/TransformAlias">
<!ENTITY XSLFO.ns "http://www.w3.org/1999/XSL/Format">
<!ENTITY copy "&#169;">
<!ENTITY trade "&#8482;">
<!ENTITY deg "&#x00b0;">
<!ENTITY gt "&#62;">
<!ENTITY sup2 "&#x00b2;">
<!ENTITY frac14 "&#x00bc;">
<!ENTITY quot "&#34;">
<!ENTITY frac12 "&#x00bd;">
<!ENTITY euro "&#x20ac;">
<!ENTITY Omega "&#937;">
]>


<xsl:stylesheet 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:func="http://exslt.org/functions"
	xmlns:exslt="http://exslt.org/common"
	xmlns:fox="http://xmlgraphics.apache.org/fop/extensions"
	xmlns:saxon="http://saxon.sf.net/" extension-element-prefixes="saxon"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xslfast="http://www.xslfast.com"
	xmlns:common="http://exslt.org/common"
	xmlns:fo="http://www.w3.org/1999/XSL/Format" version="2.0"
	xmlns:msxsl="urn:schemas-microsoft-com:xslt"
	xmlns:NS1="http://www.greco.eu/schemas/2014/GOSPOS">


<xsl:variable name="path" select="document-uri(document(''))" />
<xsl:variable name="path1" select="base-uri()" />
<xsl:variable name="path2" select="static-base-uri()" />
<xsl:variable name="path3" select="replace(base-uri(),'(.*/)[^/]+?.xml','$1')" />

<xsl:variable name="xxslfile" select="codepoints-to-string(reverse(string-to-codepoints(substring-before(codepoints-to-string(reverse(string-to-codepoints($path))), '/'))))"/> <!-- file alleine -->
<xsl:variable name="xxbasedir" select="substring-before($path2,$xxslfile)" /> <!-- Verzeichnis, von dem aus das xsl file geladen wurde -->


<xsl:variable name="common_img" select="concat($xxbasedir,'IMG','/')" />
<xsl:variable name="special_img" select="concat($xxbasedir,'..','/','IMG','/')" />

<xsl:template match="NS1:form">
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
<fo:layout-master-set>
<fo:simple-page-master master-name="pagemaster1" page-height="845.0pt" page-width="598.0pt" margin-top="0.0pt" margin-left="0.0pt" margin-bottom="0.0pt" margin-right="0.0pt" reference-orientation="0" fox:bleed="0pt" fox:crop-box="media-box" fox:crop-offset="0pt" fox:scale="1.0">
<xsl:variable name="backgroundImageRepeat">no-repeat</xsl:variable><fo:region-body margin-left="42.68pt" margin-top="113.81pt" margin-bottom="71.13pt" margin-right="42.68pt"  background-position-horizontal="left" background-position-vertical="top" />
<fo:region-before extent="113.81pt" precedence="true" />
<fo:region-after extent="71.13pt" precedence="true" />
<fo:region-start extent="42.68pt" />
<fo:region-end extent="42.68pt" />
</fo:simple-page-master>
</fo:layout-master-set>
<fo:bookmark-tree> </fo:bookmark-tree>
<fo:page-sequence master-reference="pagemaster1" format="1">
<xsl:attribute name="force-page-count">no-force</xsl:attribute>
<fo:static-content flow-name="xsl-region-before">
<fo:block-container position="fixed"  z-index="-1"  display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="100.0pt"  height="30.0pt" ><!--
<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_GrECo.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_VMG.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_BACA.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_EGHV.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_GrECo.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
   <fo:block absolute-position="absolute" top="0cm" left="0cm">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_CMV.jpg')})" content-width="21.12cm" />
   </fo:block>
</xsl:if>
-->
<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_GrECo.jpg')})" content-width="21.12cm" />
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_VMG.jpg')})" content-width="21.12cm" />
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_BACA.jpg')})" content-width="21.12cm" />
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_EGHV.jpg')})" content-width="21.12cm" />
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_GrECo.jpg')})" content-width="21.12cm" />
</xsl:if>

<xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
	    <fo:external-graphic src="url({concat($common_img,'Folgeseite_CMV.jpg')})" content-width="21.12cm"/>
</xsl:if></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="xsl-region-after">
<fo:block-container position="absolute" top="28.5pt" left="256.36pt" height="22.76pt" width="85.36pt" display-align="after" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="center" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="22.76pt" width="85.36pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value='VMG'">
	<xsl:text>Seite </xsl:text>
	<fo:page-number/>
</xsl:if></fo:block>
</fo:block-container>
<fo:block-container position="absolute" top="28.5pt" left="472.88pt" height="22.76pt" width="85.36pt" display-align="after" reference-orientation="0" fox:transform="rotate(0) , translate(0, 0)">
<fo:block text-align="end" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="8.0pt" padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" position="relative" height="22.76pt" width="85.36pt" keep-together="auto"  white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en" ><xsl:if test="NS1:item[@NS1:name='branding']/@NS1:value!='VMG'">
	<xsl:text>Seite </xsl:text>
	<fo:page-number/>
</xsl:if></fo:block>
</fo:block-container>
</fo:static-content>
<fo:static-content flow-name="xsl-region-start">
  <fo:block/>
</fo:static-content>
<fo:static-content flow-name="xsl-region-end">
  <fo:block/>
</fo:static-content>
<fo:flow flow-name="xsl-region-body">
<fo:block/>
<fo:block-container display-align="before" reference-orientation="0">
<fo:block position="relative" text-align="start" color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" white-space-collapse="false"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  hyphenate="true" language="en"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" width="436.0pt"  height="30.0pt" ><xsl:variable name="Firmenfarbe_h1_z">
<xsl:choose>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GrECo'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'VMG'">
		 <xsl:value-of select="'#E2001A'"/> <!-- Rot VMG 226,0,26-->
	</xsl:when>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'BA-CA'">
		 <xsl:value-of select="'#FF0000'"/> <!-- Rot BA-CA 255,0,0-->
	</xsl:when>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'CMV'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'EGHV'">
		 <xsl:value-of select="'#005AA1'"/> <!-- Blau GrECo 0,90,161-->
	</xsl:when>
	<xsl:when test="NS1:item[@NS1:name='branding']/@NS1:value = 'GJRC'">
		 <xsl:value-of select="'#FD6A0A'"/> <!-- Orange GrECo 253,106,10-->
	</xsl:when>
	<xsl:otherwise>
		 <xsl:value-of select="'green'"/>
	</xsl:otherwise>
</xsl:choose>
</xsl:variable>


<!--
<xsl:if test="NS1:item[@NS1:name='chk_gesamtklauseln']/@NS1:value=''">
	<xsl:call-template name="Zusammenfassung">
	</xsl:call-template>
	<fo:block page-break-after="always"></fo:block>
</xsl:if>
-->

<fo:block-container>
	<fo:block position="relative" font-family="Calibri" font-size="10pt" text-align="left">
		<fo:table text-align="left" vertical-align="center" padding-top="0.3cm" padding-bottom="0.3cm" >
			<fo:table-column column-width="24%" border="0.02cm" border-style="solid"/>
			<fo:table-column column-width="60%" border="0.02cm" border-style="solid"/>
			<fo:table-column column-width="8%" border="0.02cm" border-style="solid"/>
			<fo:table-column column-width="8%" border="0.02cm" border-style="solid"/>

<fo:table-header border-style="none">                            
      <fo:table-row >                         
        <fo:table-cell number-columns-spanned="4">
	<fo:block text-align="center" space-after="8pt">
		<fo:inline font-family="Calibri" font-size="16pt" color="{$Firmenfarbe_h1_z}">
		<xsl:text>Fragebogen</xsl:text>
		<xsl:text>&#x0a;</xsl:text>
		<xsl:choose>
			<xsl:when test="NS1:item[@NS1:name='select_insurance_cover_do']/@NS1:value = 'true' and NS1:item[@NS1:name='select_insurance_cover_srs']/@NS1:value = 'true'" >
				<xsl:text>D&amp;O und Unternehmens-Strafrechtsschutzversicherung</xsl:text>
			</xsl:when>
			<xsl:when test="NS1:item[@NS1:name='select_insurance_cover_do']/@NS1:value = 'true' and NS1:item[@NS1:name='select_insurance_cover_srs']/@NS1:value = 'false'" >
				<xsl:text>D&amp;O Versicherung</xsl:text>
			</xsl:when>
			<xsl:when test="NS1:item[@NS1:name='select_insurance_cover_do']/@NS1:value = 'false' and NS1:item[@NS1:name='select_insurance_cover_srs']/@NS1:value = 'true'" >
				<xsl:text>Unternehmens-Strafrechtsschutzversicherung</xsl:text>
			</xsl:when>			
			<xsl:otherwise>
				<xsl:text></xsl:text>
			</xsl:otherwise>
		</xsl:choose>
		</fo:inline>
	</fo:block>			
        </fo:table-cell>
     </fo:table-row>
</fo:table-header>
			
			
			
<fo:table-body>
	<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
		<fo:table-cell  font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
			<fo:block>
				<xsl:text>VersicherungsnehmerIn</xsl:text>
			</fo:block>
		</fo:table-cell>
		<fo:table-cell number-columns-spanned="3" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
			<fo:block>
				<xsl:value-of select="concat(NS1:item[@NS1:name='name_client']/@NS1:value,', ',NS1:item[@NS1:name='street_client']/@NS1:value, ', ',NS1:item[@NS1:name='zip_client']/@NS1:value, ' ', NS1:item[@NS1:name='city_client']/@NS1:value,', ',NS1:item[@NS1:name='trade_register_no_client']/@NS1:value)" />
			</fo:block>
		</fo:table-cell>
	</fo:table-row>


<!-- Frage 1 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Der Versicherungsnehmer ist in einem der im Anhang aufgelisteten Bereiche tätig?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_industry']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_industry']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 1 -->


<!-- Frage 2 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Die Versicherungsnehmerin ist ein "junges" Unternehmen (d.h. seit weniger als 2 Jahren im Firmenbuch eingetragen)?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_founded']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_founded']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 2 -->


<!-- Frage 3 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Es werden Anteile der Versicherungsnehmerin oder einer Tochtergesellschaft an einer Börse gehandelt und/oder es ist ein Börsengang geplant?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_stock']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_stock']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 3 -->


<!-- Frage 4 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Die Versicherungsnehmerin hat Tochterunternehmen in den USA/Kanada, deren (Gesamt-) Bilanzsumme 20% der konsolidierten Unternehmensbilanzsumme übersteigen?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_usa']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_usa']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 4 -->

<!-- Frage 5 --> 
<xsl:if test="NS1:item[@NS1:name='select_insurance_cover_do']/@NS1:value != 'false'" >
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Die Versicherungsnehmerin hat in den letzten zwei Geschäftsjahren einen (konsolidierten) Jahresüberschuss erwirtschaftet.</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_positive_net_income_do']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_positive_net_income_do']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 5 -->

<!-- Frage 6 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Bestehende D&amp;O Vorversicherung</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='preinsurance_do']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='preinsurance_do']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 6 -->

<!-- Frage 7 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Wurden Schadenmeldungen zu bestehenden oder früher abgeschlossenen D&amp;O Versicherungsverträgen gemacht?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_do_pre_yes']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_do_pre_yes']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 7 -->

<!-- Frage 8 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Sind in den letzten 3 Jahren Mitglieder der Geschäftsführung vorzeitig entlassen oder gekündigt worden?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_general_managers_fired_do_pre_yes']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_general_managers_fired_do_pre_yes']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 8 -->

<!-- Frage 9 -->
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>In den vergangenen 5 Jahren wurde gegen eine der zu versichernden Personen Ansprüche im Sinne der beantragten D&amp;O-Deckung geltend gemacht?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_do_pre_no']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_do_pre_no']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
<!-- Ende Frage 9 -->

<!-- Frage 10 -->
<xsl:if test="NS1:item[@NS1:name='preinsurance_do']/@NS1:value != 'true'" >
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Dem Antragssteller oder den zu versichernden Personen sind Sachverhalte bekannt, die zu einer Inanspruchnahme der beantragten Deckung führen könnten, z.B. Pflichtverletzungen im Zusammenhang mit seiner/ihrer beruflichen Tätigkeit oder unzureichender Überwachung oder Auswahl von Mitarbeitern, mangelhafter Organisation von Arbeitsprozessen oder sonstigen Tätigkeiten?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_assumed_do_pre_no']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_assumed_do_pre_no']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
</xsl:if>
</xsl:if> <!-- Ende alles D+O Teile ... -->
<!-- Ende Frage 10 -->

<!-- Frage 11 -->
<!-- doppelt wegen GUI
<xsl:if test="NS1:item[@NS1:name='preinsurance_do']/@NS1:value = 'false' or NS1:item[@NS1:name='preinsurance_do']/@NS1:value = '' " >
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Sind in den letzten 3 Jahren Mitglieder der Geschäftsführung vorzeitig entlassen oder gekündigt worden? SRS!!!</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_general_managers_fired_do_pre_no']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_general_managers_fired_do_pre_no']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
</xsl:if>
-->
<!-- Ende Frage 11 -->

<!-- Frage 12 -->
<xsl:if test="NS1:item[@NS1:name='select_insurance_cover_srs']/@NS1:value != 'false' ">
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Es wurden im Zeitraum der vergangenen 5 Jahre außerhalb des Straßenverkehrs Straf- oder Verwaltungsstrafverfahren eingeleitet?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_srs']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_srs']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
</xsl:if>
<!-- Ende Frage 12 -->

<!-- Frage 13 -->
<xsl:if test="NS1:item[@NS1:name='select_insurance_cover_srs']/@NS1:value != 'false' ">
<fo:table-row padding-top="0.3cm" padding-bottom="0.3cm" border="0.02cm" border-style="solid">
	<fo:table-cell number-columns-spanned="2" font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block>
			<xsl:text>Dem Antragssteller oder den zu versichernden Personen sind Anzeichen für bevorstehende Straf- oder Verwaltungsstrafverfahren außerhalb des Straßenverkehrs bekannt?</xsl:text>
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
		<xsl:text>Ja </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_assumed_srs']/@NS1:value='ja'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>
	<fo:table-cell font-weight="bold" padding-top="0.3cm" padding-bottom="0.3cm" padding-left="0.3cm">
		<fo:block padding-top="0.02cm">
			<xsl:text>Nein </xsl:text>
			<xsl:choose>
				<xsl:when test="NS1:item[@NS1:name='ko_question_open_claims_assumed_srs']/@NS1:value='nein'">
					<fo:inline font-family="Arial Unicode MS">&#x2611;</fo:inline>
				</xsl:when>
				<xsl:otherwise>
					<fo:inline font-family="Arial Unicode MS">&#x2610;</fo:inline>
				</xsl:otherwise>
			</xsl:choose>	
		</fo:block>
	</fo:table-cell>	
</fo:table-row>
</xsl:if>
<!-- Ende Frage 13 -->

				
	</fo:table-body>
</fo:table>
</fo:block>		
</fo:block-container>

<fo:block space-before="1.5cm">
<xsl:call-template name="signature" />
</fo:block>

<fo:block page-break-before="always" margin-left="2cm">
<xsl:call-template name="Unternehmensbereiche" />
</fo:block></fo:block>
</fo:block-container>
<xsl:if test='position()=last()'>
  <fo:block id="lastPage"/>
</xsl:if>
</fo:flow>
</fo:page-sequence>
</fo:root>
</xsl:template>

<!-- GENERATED TEMPLATE Unternehmensbereiche -->
<xsl:template name="Unternehmensbereiche" >
<fo:block break-before="auto"/>
<fo:block-container height="30.0pt" width="477.0pt" font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="start" width="477.0pt"  height="30.0pt"  keep-together="auto"  letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="14.0pt" font-weight="bold" text-decoration="underline">
<fo:inline text-decoration="underline"><xsl:text>ANHANG</xsl:text></fo:inline></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="14.0pt" font-weight="bold" text-decoration="underline">
<xsl:text>
</xsl:text></fo:inline>
</fo:block>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="14.0pt" font-weight="bold" text-decoration="underline">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" font-weight="bold" text-decoration="underline">
<fo:inline text-decoration="underline"><xsl:text>Liste mit Unternehmensbereichen:</xsl:text></fo:inline></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Abfallwirtschaft</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Architekten</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Ärzte</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Bauhauptgewerbe </xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Baumeister </xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Biotechnologie</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Chemie</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Erneuerbare Energie</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Finanzdienstleister</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Flughäfen</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>KfZ Zulieferer (mehr als 80% des Umsatzes wird in diesem Bereich erwirtschaftet) </xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Körperschaften öffentlichen Rechts </xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Krankenhäuser</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Lebensmittelerzeugung (ausgenommen: Herstellung von landwirtschaftlichen Produkten) </xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Medienindustrie </xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Medizintechnik </xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Mineralölherstellung</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Notare</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Pflegeheime</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Pharma</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Planungsbüros</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Politiker</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Politische Parteien</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Profi-Sport</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Raffinerie</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Rechtsanwälte</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Sanatorien</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Security Unternehmen</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Spedition/Frachtführer </xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Sportvereine und Profi-Sport</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Steuerberater</xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Tabak- und Zigarettenproduktion</xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Telekommunikation </xsl:text></fo:inline>
<fo:block text-align="left" white-space-collapse="false"  hyphenate="true" language="en"  linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed" >
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
</fo:inline>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Wettbüros </xsl:text></fo:inline>
</fo:block>
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Wirtschaftstreuhänder</xsl:text></fo:inline>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>

<!-- GENERATED TEMPLATE signature -->
<xsl:template name="signature" >
<fo:block break-before="auto"/>
<fo:block-container  reference-orientation="0" >
<fo:block keep-together="auto" ><!-- GENERATE TABLE START-->

<fo:table table-layout="fixed" width="100%">
<fo:table-column column-width="256.07pt" />
<fo:table-column column-width="256.07pt" />
<fo:table-body>
<xsl:for-each select=".">

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="after" width="256.07pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="center" keep-together="auto"  color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>-----------------------------------------------------------</xsl:text></fo:inline>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="after" width="256.07pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="center" keep-together="auto"  color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>-----------------------------------------------------------</xsl:text></fo:inline>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="256.07pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="center" keep-together="auto"  color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Ort, Datum</xsl:text></fo:inline>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>
<fo:table-cell padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" display-align="before" width="256.07pt"  reference-orientation="0">
<fo:block break-before="auto"/>
<fo:block-container font-stretch="normal" text-transform="none">
<fo:block linefeed-treatment="preserve" white-space-treatment="ignore-if-surrounding-linefeed"  padding-bottom="0.0pt" start-indent="0.0pt" end-indent="0.0pt" padding-top="0.0pt" padding="0.0pt" line-height="14.5pt" white-space-collapse="false"  hyphenate="true" language="en"  text-align="center" keep-together="auto"  color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt" letter-spacing="normal" word-spacing="normal" font-stretch="normal" text-transform="none">
<fo:inline color="rgb-icc(0,0,0, #CMYK, 0.65,0.53,0.51,1.0)" font-family="Calibri" font-size="11.0pt">
<xsl:text>Unterschrift</xsl:text></fo:inline>
</fo:block>
</fo:block-container>
<fo:block break-after="auto"/>
</fo:table-cell>

    </fo:table-row>

    <fo:table-row>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>
    <fo:table-cell>
         <fo:block/>
    </fo:table-cell>

    </fo:table-row>
</xsl:for-each></fo:table-body>
</fo:table>
</fo:block></fo:block-container>
<fo:block break-after="auto"/>
</xsl:template>
<xsl:template match="include-xsl-fo">
    <xsl:copy-of select="@*"/>
</xsl:template>
</xsl:stylesheet>
